name: shellcheck

permissions:
  checks: write

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo -e '#!/bin/bash\n' >> package.json_temp.sh
      - run: jq -r '.scripts[]' package.json >> package.json_temp.sh
      - run: cat package.json_temp.sh
      - name: ShellCheck Action
        uses: fearphage/shellcheck-action@95d2a3d34d381a7314c286ea1725ca8cce3b51fd
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
